### ISSUE TITLE
Preloading pages?

### ISSUE THREAD

**Issue by FCrane** [tophf/autopagerize#1]
Hi!

Great extension, but it's extremely slow because it does not preload the next (2,3,5, etc.) pages automatically! There should be an option to make it preload several pages, so that I don't have to wait for the next page to be loaded when I scroll down to the bottom of the current one.

Thx!

**Comment by tophf** [comment]
I didn't comment earlier because I had no idea how to implement this rare feature without introducing new concepts or complicating the code. I think I've just found a trivial solution: now there's an option to customize the remaining page height. The default value is `400` pixels inherited from the original AutoPagerize. You can try increasing it to `4000` or even `40000`.
